### ISSUE TITLE
R 3.5.2?

### ISSUE THREAD

**Issue by kendonB** [thequackdaddy/R-OpenBLAS#7]
Is out now. Struggling to work out how to change the r-source submodule to a different specific commit.

**Comment by thequackdaddy** [comment]
This is all I typed... let's see what happens ...

```
cd r-source
git checkout -t origin/tags/R-3-5-2
cd ..
git add r-source
git commit -m "Upgrade R to 3.5.2"
git push origin master
git tag "v3.5.2"
git push --tags
```

The executable will be on appveyor soon and in the release section here.
